name: build
on: push
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            
            - name: Install dependencies
              run: pip install poetry

            - name: Set up project
              run: make install

            - name: Run linter
              run: make lint